name: deplot-vibebooks-api

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Definir Nome da Imagem (Lowercase)
        run: |
          # Pega o nome do repo, converte para minúsculo e salva na variável de ambiente
          echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir e Criar Imagem Docker
        run: |
          docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Instalar Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Deploy no Kubernetes (K3s)
        run: |
          sed -i "s|image: ghcr.io/.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest|g" k8s/deployment.yaml
          
          kubectl apply -f k8s/deployment.yaml
          
          kubectl rollout restart deployment/vibebooks-api -n vibebooks-api-prod
